import java.security.KeyStore;
import java.util.Scanner;

public class Main {
    public static void main(String[] args)
    {
        Scanner Input = new Scanner(System.in);
        int GuessNumberByTheUser = 0;
        //To generate a random number use The Following Math.random()
        int RandomNumber = (int)(Math.random()*1000);
        System.out.printf("The Random Number Generated by the system is %d\n",RandomNumber);
        boolean IsCorrect = true;//Flag Controlled Statement
        while(IsCorrect)
        {
            System.out.println("Please enter a number between 1 and 100.");
            GuessNumberByTheUser = Input.nextInt();
            if(GuessNumberByTheUser < RandomNumber)
                System.out.println("Number is too Small");
            else if(GuessNumberByTheUser > RandomNumber)
                System.out.println("Number is too Big");
            else
            {
                System.out.println("You win");
                IsCorrect = false;
            }
        }

    }
}